### ISSUE TITLE
Solo API Project コメント

### ISSUE THREAD

**Issue by nasi-goreng** [hi-miyashita/CC-API-Solo-Project#12]
@hi-miyashita さん、プロジェクトお疲れ様でした！

短期間での開発お疲れ様でした 👏

いくつかコメントをさせていただきました！

- knexの設定で上手く行かなかったとのことですが、ローカルで確認したところ、環境変数が上手く読み込まれてないみたいでした！
    - `npm run migrate`をするときと、`npm run dev`をしたときで、`dotenv`が読みに行くパスが変わるようです。
    - 対応方法はいくつかあると思いますが、こちらの設定で上手くいきました！
        - `.env.local`と`knexfile.js`を`dataAccess`フォルダ内に置く
        - `knexfile.js`内で以下のようにパスを指定する
        
        ```jsx
        // knexfile.js
        const path = require('path');
        const ENV_PATH = path.join(__dirname, './.env.local');
        require('dotenv').config({
          debug: true,
          path: ENV_PATH,
        });
        ```
        
        - `dotenv`の`config`で上にあるように、`debug: true`とすると、エラー時の読み込む際のパスが表示されて便利です
- 非同期の書き方にも一部正しく動作しないところがあったようで、こちらも書き方を何通りかありますが、今回のように`server.js`で`await`をするのであれば、`plantController.js`の各メソッドで`return`を書くと良いかと思います！
- server.jsでしっかりtry…catchでエラーハンドリングを行い、適切なステータスコードを返していて素晴らしいです🙌
- エンドポイントもrestfulを意識されていて良いですね👍
- この短時間で、テストも実装し、コントローラーのファイル分割されていて素晴らしいです！ぜひコース終了後も納得のいくところまで実装したり、新しく再構築してみてください！

以上です！お疲れ様でした〜

**Comment by hi-miyashita** [comment]
確認ありがとうございます！
環境変数の読み込みに問題があったんですね。

debug: trueとすると、エラー時の読み込む際のパスが表示されて便利です
参考にします。ありがとうございます。
